@JWTToken = "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3Nzc0Njk5MzUsIm5hbWUiOiJNdW55YSIsInN1YiI6IjY3ODBiOTllLWNmZGItNDQ1Yi05MTU0LTFhMzg5ZDM3OWYwZCJ9.VV90IobiKdRfZsANDCbOQ5e2fwQWnjqB7q253HOD7eg"

@URL = "http://127.0.0.1:8000"

@user_id = "6780b99e-cfdb-445b-9154-1a389d379f0d"

curl -X POST {{URL}}/users/register \
     -H "Content-Type: application/json" \
     -d '{
    "name": "Munya",
    "phone_number" : "+27627197691",
    "password" : "munya456"
    }'


###
curl -X POST {{URL}}/users/login \
     -H "Content-Type: application/json" \
     -d '{
    "phone_number" : "+27627197691",
    "password" : "munya456"
    }'

###
curl -X PUT {{URL}}/api/uu/ts/{{user_id}} \
     -H {{JWTToken}} \
     -H "Content-Type: application/json" \
     -d '{
    "score": 2
    }'

###
curl -X PUT {{URL}}/api/uu/at/{{user_id}} \
     -H {{JWTToken}} \
     -H "Content-Type: application/json" \
     -d '{
    "option": "start"
    }'
